name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: latest
            python_version: "3.9"
          - name: python3.9
            python_version: "3.9"
          - name: python3.8
            python_version: "3.8"
          - name: python3.7
            python_version: "3.7"
          - name: python3.6
            python_version: "3.6"
          - name: python3.9-slim
            python_version: "3.9"
          - name: python3.8-slim
            python_version: "3.8"
          - name: python3.9-alpine3.14
            python_version: "3.9"
          - name: python3.8-alpine3.10
            python_version: "3.8"
          - name: python3.7-alpine3.8
            python_version: "3.7"
          - name: python3.6-alpine3.8
            python_version: "3.6"
      fail-fast: true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install Dependencies
        run: python3.7 -m pip install "docker>=4.4.4,<5.0.0" "pytest>=6.2.4,<7.0.0"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1  
      - name: Configure Buildx
        run: docker buildx create --use 
      - name: Deploy Image
        run: bash scripts/build-push.sh
        env:
          REPO: ${{ secrets.DOCKER_REPO }}
          NAME: ${{ matrix.image.name }}
          DOCKERFILE: ${{ matrix.image.dockerfile }}
          PYTHON_VERSION: ${{ matrix.image.python_version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
